version: '3.3'

services:

  jti_udp_logstash:
    build: ./inputs/logstash/image
    container_name: jti_udpNative
    ports:
      - "50000:50000/udp"
    env_file:
      - 'inputs/logstash/jti_udpNative/data/env.influxdb_logstash'
    volumes:
      - ./inputs/logstash/jti_udpNative/data:/var/tmp/data
      - ./inputs/logstash/jti_udpNative/templates:/var/tmp/templates
    links:
      - influxdb

  jti_openconfig_logstash:
    build: ./inputs/logstash/image
    container_name: jti_openConfig
    ports:
      - "50051:50051/tcp"
    env_file:
      - 'inputs/logstash/jti_openConfig/data/env.influxdb_logstash'
    volumes:
      - ./inputs/logstash/jti_openConfig/data:/var/tmp/data
      - ./inputs/logstash/jti_openConfig/templates:/var/tmp/templates
    links:
      - influxdb
  
  input-netflow:
    build: ./inputs/logstash/image
    container_name: input-netflow
    ports:
      - "2055:2055/udp"
    volumes:
      - ./inputs/logstash/input-netflow/data:/var/tmp/data
      - ./inputs/logstash/input-netflow/templates:/var/tmp/templates
    links:
      - influxdb

  influxdb:
    image: influxdb:1.6.4
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8090:8090"
    volumes:
      - influxdb_data_logstash:/var/lib/influxdb
      - ./outputs/influxdb/image/config/influxdb.sh:/docker-entrypoint-initdb.d/influxdb.sh
  
  chronograf:
    image: quay.io/influxdb/chronograf:1.5.0.1
    container_name: chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086/
      KAPACITOR_URL: http://kapacitor:9092/
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor

  kapacitor:
    image: kapacitor:1.5.0
    container_name: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086/
    ports:
      - "9092:9092"
    links:
      - influxdb

  grafana:
    image: grafana/grafana:5.3.2
    container_name: grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes:
      - ./web_ui/grafana/dashboards/logstash:/var/tmp
      - ./web_ui/grafana/image/config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./web_ui/grafana/image/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.49.232.211 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logstash-jti-udp:1:1,logstash-jti-oc:1:1,logstash-netflow:1:1"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HEAP_SIZE=3g"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
      image: docker.elastic.co/kibana/kibana-oss:6.5.0
      container_name: kibana
      environment:
        SERVER_NAME: kibana
        ELASTICSEARCH_URL: http://elasticsearch:9200/
      ports:
        - 5601:5601
      ulimits:
        nproc: 65535
        memlock:
          soft: -1
          hard: -1
      cap_add:
        - ALL
volumes:
  esdata:
  influxdb_data_logstash:
