{
 "title": "Data Collection Agent Dashboard",
 "tags": [
  "netconf",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_regex",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  { "title": "TASK MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "task memory (percent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).task.memory.current-percent/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "task memory (size)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from /($host_regex).task.memory.current-size/ where $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Routing Engine statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "RE - CPU idle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).chassis.routing-engine.*.cpu-idle/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.chassis.routing-engine.*.cpu-idle/"
      }
     ]
    },
    {
     "title": "RE - Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).chassis.routing-engine.*.memory-buffer-utilization/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.chassis.routing-engine.*.memory-buffer-utilization/"
      }
     ]
    },
    {
     "title": "RE - buffers.in_use.current_mbuf",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.system.buffers.in_use.current_mbuf/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.system.buffers.in_use.current_mbuf/"
      }
     ]
    },
    {
     "title": "RE - buffers.clusters_in_use.current_mbuf_clusters",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.system.buffers.clusters_in_use.current_mbuf_clusters/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.system.buffers.clusters_in_use.current_mbuf_clusters/"
      }
     ]
    }
   ]
  },
  {
   "title": "Routing Table Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active routes (inet.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.0.actives/"
      }
     ]
    },
    {
     "title": "Active routes (inet.3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.actives/"
      }
     ]
    },
    {
     "title": "Actives routes (bgp.l3vpn.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.actives/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.actives/"
      }
     ]
    },
    {
     "title": "Hidden routes (inet.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.0.hidden/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.0.hidden/"
      }
     ]
    },
    {
     "title": "Hidden routes (inet.3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.inet.3.hidden/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.inet.3.hidden/"
      }
     ]
    },
    {
     "title": "Hidden routes (bgp.l3vpn.0)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).route-table.summary.bgp.l3vpn.0.hidden/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.route-table.summary.bgp.l3vpn.0.hidden/"
      }
     ]
    }
   ]
  },
  {
   "title": "RE PROCESSES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.rpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.rpd-SIZE/"
      }
     ]
    },
    {
     "title": "COSD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.cosd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.cosd-SIZE/"
      }
     ]
    },
    {
     "title": "DFWD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.dfwd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.dfwd-SIZE/"
      }
     ]
    },
    {
     "title": "DCD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.dcd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.dcd-SIZE/"
      }
     ]
    },
    {
     "title": "MIB2D SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.mib2d-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.mib2d-SIZE/"
      }
     ]
    },
    {
     "title": "SNMPD SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.snmpd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.snmpd-SIZE/"
      }
     ]
    },
    {
     "title": "SMID SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.smid-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.smid-SIZE/"
      }
     ]
    },
    {
     "title": "SMI-HELPER SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.smihelperd-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.smihelperd-SIZE/"
      }
     ]
    },
    {
     "title": "SAMPLED SIZE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).re.memory.sampled-SIZE/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.re.memory.sampled-SIZE/"
      }
     ]
    }
   ]
  },
  {
   "title": "PFE LOCAL STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "pfe-local-traffic-stats.pfe-packets (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.pfe-.*-packets/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.pfe-.*-packets/"
      }
     ]
    },
    {
     "title": "hardware-input-drops (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.hardware-input-drops/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.hardware-input-drops/"
      }
     ]
    },
    {
     "title": "software-input-control-drops (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-control-drops/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-control-drops/"
      }
     ]
    },
    {
     "title": "software-input-high-drops (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-high-drops/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-high-drops/"
      }
     ]
    },
    {
     "title": "software-input-medium-drops (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-medium-drops/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-medium-drops/"
      }
     ]
    },
    {
     "title": "software-input-low-drops (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-low-drops/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-local-traffic-stats.software-input-low-drops/"
      }
     ]
    }
   ]
  },
  {
   "title": "PFE TRANSIT STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "pfe-packets (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-traffic-stats.pfe-.*-packets/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-traffic-stats.pfe-.*-packets/"
      }
     ]
    },
    {
     "title": "pfe-pps (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).pfe-general-stats.aggregated.pfe-traffic-stats.*-pps/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-traffic-stats.*-pps/"
      }
     ]
    },
    {
     "title": "PFE bits-to-test-discards (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.bits-to-test-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.bits-to-test-discard/"
      }
     ]
    },
    {
     "title": "PFE data-error-discard (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.data-error-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.data-error-discard/"
      }
     ]
    },
    {
     "title": "PFE stack-underflow-discard (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-underflow-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-underflow-discard/"
      }
     ]
    },
    {
     "title": "PFE stack-overflow-discard (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-overflow-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.stack-overflow-discard/"
      }
     ]
    },
    {
     "title": "PFE bad-route-discards (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.bad-route-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.bad-route-discard/"
      }
     ]
    },
    {
     "title": "PFE nexthop-discard (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex)..pfe-general-stats.aggregated.pfe-hardware-discards-stats.nexthop-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.nexthop-discard/"
      }
     ]
    },
    {
     "title": "PFE invalid-iif-discards (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.invalid-iif-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.invalid-iif-discard/"
      }
     ]
    },
    {
     "title": "PFE info-cell-discards (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.info-cell-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.info-cell-discard/"
      }
     ]
    },
    {
     "title": "PFE fabric-discards (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.fabric-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.fabric-discard/"
      }
     ]
    },
    {
     "title": "PFE timeout-discads (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.timeout-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.timeout-discard/"
      }
     ]
    },
    {
     "title": "PFE truncated-key-discard (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).pfe-general-stats.aggregated.pfe-hardware-discards-stats.truncated-key-discard/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.pfe-general-stats.aggregated.pfe-hardware-discards-stats.truncated-key-discard/"
      }
     ]
    }
   ]
  },
  {
   "title": "PFE Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "used-heap-mem-percent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).fpc.slot.*.resource.used-heap-mem-percent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.fpc.slot.*.resource.used-heap-mem-percent/"
      }
     ]
    },
    {
     "title": "used-ifl-counter-percent per PFE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).fpc.slot.*.pfe.*.resource.used-ifl-counter-percent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-ifl-counter-percent/"
      }
     ]
    },
    {
     "title": "used-filter-counter-percent per PFE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).fpc.slot.*.pfe.*.resource.used-filter-counter-percent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.fpc.slot.*.pfe.*.resource.used-filter-counter-percent/"
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP total packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/$host_regex.snmp-.*-packets/",
       "query": "SELECT mean(\"delta\") from /($host_regex).snmp-.*-packets/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SNMP get-next packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/$host_regex.snmp-input-get-nexts/",
       "query": "SELECT mean(\"delta\") from /($host_regex).snmp-input-get-nexts/ WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "delta" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ISIS STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "ISIS Total packets-sent (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.Totals.packets-sent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.Totals.packets-sent/"
      }
     ]
    },
    {
     "title": "ISIS Total packets-received (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.Totals.packets-received/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.Totals.packets-received/"
      }
     ]
    },
    {
     "title": "ISIS Total packets-retransmitted (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.Totals.packets-retransmitted/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.Totals.packets-retransmitted/"
      }
     ]
    },
    {
     "title": "ISIS Total packets-dropped (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.Totals.packets-dropped/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.Totals.packets-dropped/"
      }
     ]
    },
    {
     "title": "ISIS Total packets-processed (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.Totals.packets-processed/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.Totals.packets-processed/"
      }
     ]
    },
    {
     "title": "ISIS fragments-rebuilt (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.general.fragments-rebuilt/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.general.fragments-rebuilt/"
      }
     ]
    },
    {
     "title": "ISIS spf-runs (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.general.spf-runs/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.general.spf-runs/"
      }
     ]
    },
    {
     "title": "ISIS LSP regenerations (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).protocols.isis.statistics.general.lsps-regenerated/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.isis.statistics.general.lsps-regenerated/"
      }
     ]
    }
   ]
  },
  {
   "title": "BGP STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "bgp peer-count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).protocols.bgp.summary.peer-count/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.bgp.summary.peer-count/"
      }
     ]
    },
    {
     "title": "bgp group-count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).protocols.bgp.summary.group-count/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.bgp.summary.group-count/"
      }
     ]
    },
    {
     "title": "bgp down-peer-count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).protocols.bgp.summary.down-peer-count/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.protocols.bgp.summary.down-peer-count/"
      }
     ]
    }
   ]
  },
  {
   "title": "BNG Subscribers Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "BNG total subscribers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 157 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.by-port.port-total/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.by-port.port-total/"
      }
     ]
    },
    {
     "title": "BNG l2tp-sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 157 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.l2tp-sessions/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.l2tp-sessions/"
      }
     ]
    },
    {
     "title": "BNG l2tp-tunnels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 164 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.l2tp-tunnels/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.l2tp-tunnels/"
      }
     ]
    },
    {
     "title": "BNG session-state-init",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 164 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.session-state-init/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.session-state-init/"
      }
     ]
    },
    {
     "title": "BNG session-state-configured",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 171 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.session-state-configured/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.session-state-configured/"
      }
     ]
    },
    {
     "title": "BNG session-state-terminating",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 171 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.session-state-terminating/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.session-state-terminating/"
      }
     ]
    },
    {
     "title": "BNG session-state-terminated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.subscribers.summary.session-state-terminated/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.subscribers.summary.session-state-terminated/"
      }
     ]
    }
   ]
  },
  {
   "title": "BNG PPPoE Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "padi-received (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.padi-received/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.padi-received/"
      }
     ]
    },
    {
     "title": "pado-sent (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.pado-sent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.pado-sent/"
      }
     ]
    },
    {
     "title": "padr-received (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.padr-received/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.padr-received/"
      }
     ]
    },
    {
     "title": "pads-sent (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.pads-sent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.pads-sent/"
      }
     ]
    },
    {
     "title": "padt-received (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.padt-received/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.padt-received/"
      }
     ]
    },
    {
     "title": "padt-sent (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.pppoe.statistics.padt-sent/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.pppoe.statistics.padt-sent/"
      }
     ]
    }
   ]
  },
  {
   "title": "BNG RADIUS AUTH STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "authentication-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 194 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.authentication-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.authentication-requests/"
      }
     ]
    },
    {
     "title": "authentication-rollover-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 194 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.authentication-rollover-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.authentication-rollover-requests/"
      }
     ]
    },
    {
     "title": "authentication-retransmissions (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.authentication-retransmissions/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.authentication-retransmissions/"
      }
     ]
    },
    {
     "title": "authentication - accepts (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accepts/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accepts/"
      }
     ]
    },
    {
     "title": "authentication rejects (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 208 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.rejects/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.rejects/"
      }
     ]
    },
    {
     "title": "authentication-timeouts (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 208 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.authentication-timeouts/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.authentication-timeouts/"
      }
     ]
    },
    {
     "title": "authentication-packets-dropped (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 215 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.authentication-packets-dropped/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.authentication-packets-dropped/"
      }
     ]
    }
   ]
  },
  {
   "title": "BNG RADIUS ACCT STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "accounting-start-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 216 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-start-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-start-requests/"
      }
     ]
    },
    {
     "title": "accounting-interim-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 216 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-interim-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-interim-requests/"
      }
     ]
    },
    {
     "title": "accounting-stop-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 223 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-stop-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-stop-requests/"
      }
     ]
    },
    {
     "title": "accounting-rollover-requests (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 223 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-rollover-requests/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-rollover-requests/"
      }
     ]
    },
    {
     "title": "accounting-retransmissions (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 230 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-retransmissions/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-retransmissions/"
      }
     ]
    },
    {
     "title": "accounting-interim-response (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 230 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-interim-response/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-interim-response/"
      }
     ]
    },
    {
     "title": "accounting-stop-response (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 237 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-stop-response/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-stop-response/"
      }
     ]
    },
    {
     "title": "accounting-timeouts (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 237 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.radius-servers-stats.*.accounting-timeouts/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.radius-servers-stats.*.accounting-timeouts/"
      }
     ]
    }
   ]
  },
  {
   "title": "BNG POOL STATISTICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "pool.pool-usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 238 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.aaa.stats.address-assignment.pool.pool-usage/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.stats.address-assignment.pool.pool-usage/"
      }
     ]
    },
    {
     "title": "pool.out-of-addresses (delta/sec)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 238 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "delta",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(value),1s) from /($host_regex).bng.aaa.stats.address-assignment.pool.out-of-addresses/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.stats.address-assignment.pool.out-of-addresses/"
      }
     ]
    },
    {
     "title": "pool.used-addresses",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 245 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).bng.aaa.stats.address-assignment.pool.used-addresses/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.bng.aaa.stats.address-assignment.pool.used-addresses/"
      }
     ]
    }
   ]
  },
  {
   "title": "CGNAT statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "total-flows-active per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 246 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.flow-analysis.*.num-total-flows-active/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.flow-analysis.*.num-total-flows-active/"
      }
     ]
    },
    {
     "title": "num-created-flows-per-sec per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 246 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.flow-analysis.*.num-created-flows-per-sec/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.flow-analysis.*.num-created-flows-per-sec/"
      }
     ]
    },
    {
     "title": "num-created-flows-per-sec per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 253 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.flow-analysis.*.num-deleted-flows-per-sec/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.flow-analysis.*.num-deleted-flows-per-sec/"
      }
     ]
    },
    {
     "title": "num-total-subs-active per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 253 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.subscriber-analysis..*.num-total-subs-active/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.subscriber-analysis..*.num-total-subs-active/"
      }
     ]
    },
    {
     "title": "num-created-subs-per-sec per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 260 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.subscriber-analysis..*.num-created-subs-per-sec/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.subscriber-analysis..*.num-created-subs-per-sec/"
      }
     ]
    },
    {
     "title": "num-deleted-subs-per-sec per NPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 260 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "column": "value",
       "function": "mean",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).cgnat.subscriber-analysis..*.num-deleted-subs-per-sec/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "series": "/$host_regex.cgnat.subscriber-analysis..*.num-deleted-subs-per-sec/"
      }
     ]
    }
   ]
  },
  {
   "title": "RPM Probes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM Probes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "measurement": "/$host_regex$/.rpm.*.max-delay",
       "query": "select mean(value) from /($host_regex).rpm.*.max-delay/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(value) from /($host_regex).rpm.*.min-delay/ where $timeFilter group by time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}